// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnshMj47HBy0u7_LuS56pl9HbyyV8u6m8',
    appId: '1:312993905854:web:46ec979e5a8d4cbf56f2ef',
    messagingSenderId: '312993905854',
    projectId: 'water-monitory-jjtronic',
    authDomain: 'water-monitory-jjtronic.firebaseapp.com',
    databaseURL: 'https://water-monitory-jjtronic-default-rtdb.firebaseio.com',
    storageBucket: 'water-monitory-jjtronic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFq5T0FFL-8-FGuwtHHOw4RXSlC30IQCY',
    appId: '1:312993905854:android:cc97c542ba7b94d856f2ef',
    messagingSenderId: '312993905854',
    projectId: 'water-monitory-jjtronic',
    databaseURL: 'https://water-monitory-jjtronic-default-rtdb.firebaseio.com',
    storageBucket: 'water-monitory-jjtronic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YbAovLTOtOM2FpgpVV_BGINtY3aav40',
    appId: '1:312993905854:ios:93ba99185bd43c3b56f2ef',
    messagingSenderId: '312993905854',
    projectId: 'water-monitory-jjtronic',
    databaseURL: 'https://water-monitory-jjtronic-default-rtdb.firebaseio.com',
    storageBucket: 'water-monitory-jjtronic.appspot.com',
    iosClientId: '312993905854-q7qsfbebgkgha926qi8f774v1ttr4r3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterProject',
  );
}
